services:

  db:
    image: postgres:18-alpine
    container_name: securevault_db
    restart: unless-stopped

    environment:
      POSTGRES_USER: securevault_admin
      POSTGRES_PASSWORD: securevault_password
      POSTGRES_DB: securevault_db
    
    ports:
      - "5432:5432"

    expose:
      - 5432

    volumes:
      - pg_data:/var/lib/postgresql/data
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U securevault_admin -d securevault_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    
  backend:
    build: ./backend 
    container_name: securevault_backend
    ports:
      - "8000:8000"
    
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=postgresql://securevault_admin:securevault_password@db:5432/securevault_db
      - SECRET_KEY=aaf5d81275ed869da69916e26112da960375af8ad1872a3f4fa587434d794a69


    depends_on:
      db:
        condition: service_healthy

    command: ["fastapi", "dev", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - ./backend:/backend
      - /backend/.venv
    develop:
      watch:
        - action: rebuild
          path: ./backend/Dockerfile

        - action: rebuild
          path: ./backend/pyproject.toml

        - action: rebuild
          path: ./backend/uv.lock
    
  frontend:
    build: ./frontend
    container_name: securevault_frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
      - /frontend/.pnpm-store
    
    depends_on:
      backend:
        condition: service_started
      db:
        condition: service_healthy

    develop:
      watch:
        - action: rebuild
          path: ./frontend/pnpm-lock.yaml
        - action: rebuild
          path: ./frontend/Dockerfile

    
volumes:
  pg_data:
